apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-applicationset
  namespace: argocd
  metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"  # Replace with your app's metric port
    prometheus.io/path: "/metrics" # Optional, default is /metrics

spec:
  generators:
  - git:
      repoURL: https://github.com/FrenkyFix1987/gitops.git
      revision: HEAD
      directories:
        - path: apps/*
  template:
    metadata:
      name: 'app-{{ path.basename }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/FrenkyFix1987/gitops.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'ns-{{ path.basename }}'
      syncPolicy:
        automated: 
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
