apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.policy.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.statefulset.name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: {{ .Values.deployment.name }}
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: {{ .Values.policy.selector.name }}
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: {{ .Values.policy.selector.name }}
            app.kubernetes.io/component: {{ .Values.policy.selector.component }}
      ports:
        - protocol: TCP
          port: {{ .Values.statefulset.image.port }}