apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceFrontend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.serviceFrontend.type }}
  selector:
    app: {{ .Values.serviceFrontend.selector.app }}
  ports:
    - port: {{ .Values.serviceFrontend.port }}
      targetPort: {{ .Values.serviceFrontend.port }}
      protocol: TCP