apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceBackend.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.serviceBackend.type }}
  selector:
    app: {{ .Values.serviceBackend.selector.app }}
  ports:
    - port: {{ .Values.serviceBackend.port }}
      targetPort: {{ .Values.serviceBackend.targetPort }}
      protocol: TCP